version: 2
jobs:
  push:
    docker:
      - image: circleci/golang:1.9.2
    working_directory: /go/src/github.com/ymgyt/illaoi
    steps:
      - run:
          name: install aws-cli
          command: |
            pip install awscli --upgrade
            aws --version

      - run:
          name: push image
          command: |
            export AWS_ACCESS_KEY_ID=${CI_AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${CI_AWS_SECRET_ACCESS_KEY}
            docker build -t illaoi .
            docker tag illaoi:latest ${DOCKER_REPO}/illaoi:latest
            login_cmd=$(aws ecr get-login --no-include-email --region ${AWS_REGION})
            eval ${login_cmd}
            docker push ${DOCKER_REPO}/illaoi:latest
