version: 2
jobs:
  push:
    docker:
      - image: circleci/golang:1.9.2
    working_directory: /go/src/github.com/ymgyt/illaoi
    steps:

      - run: echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - run: 
          name: install python3
          command: sudo apt-get -y install python3 python3-pip

      - run:
          name: install aws-cli
          command: |
            pip3 install awscli --upgrade
            aws --version

      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: push image
          command: |
            export AWS_ACCESS_KEY_ID=${CI_AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${CI_AWS_SECRET_ACCESS_KEY}
            docker build -t illaoi .
            docker tag illaoi:latest ${DOCKER_REPO}/illaoi:latest
            login_cmd=$(/home/circleci/.local/bin/aws ecr get-login --no-include-email --region ${AWS_REGION})
            eval ${login_cmd}
            docker push ${DOCKER_REPO}/illaoi:latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - push:
          filters:
            branches:
              only:
                - master
